# Generated by Django 5.2.9 on 2025-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='attendance_records.course'),
        ),
    ]
