# Generated by Django 5.2.9 on 2025-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0003_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_data',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('E', 'Late')], default='P', max_length=1),
        ),
    ]
