# Generated by Django 5.2.9 on 2025-12-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0004_student_passport_data_alter_attendancerecord_status'),
    ]

    operations = [
    ]
