# Generated by Django 5.2.9 on 2025-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0005_auto_20251203_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_data',
            field=models.CharField(default='', max_length=128),
        ),
    ]
