# Generated by Django 5.2.9 on 2025-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0007_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.AddField(
            model_name='tutor',
            name='passport_data',
            field=models.CharField(default='', max_length=128),
        ),
    ]
