# Generated by Django 5.2.9 on 2025-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0008_remove_tutor_password_tutor_passport_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('E', 'Excused')], default='P', max_length=1),
        ),
    ]
